apiVersion: apps/v1
kind: Deployment
metadata:
  name: loanRequest
  #navespace: mybank
  labels:
    app: loanRequest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loanRequest
  template:
    metadata:
      labels:
        app: loanRequest
    spec:
      containers:
        - name: loanRequest
          image: 052937454741.dkr.ecr.ap-northeast-1.amazonaws.com/loanRequest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
---

apiVersion: v1
kind: Service
metadata:
  name: loanRequest
  #navespace: mybank
  labels:
